# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/daniele/Scrivania/Task4/project_Task4_v2.1.1/project_Task4.cache/wt [current_project]
set_property parent.project_path /home/daniele/Scrivania/Task4/project_Task4_v2.1.1/project_Task4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo /home/daniele/Scrivania/Task4/project_Task4_v2.1.1/project_Task4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/daniele/Scrivania/Task4/project_Task4_v2.1.1/project_Task4.srcs/sources_1/ip/AXI4_Stream_Divider_m/AXI4_Stream_Divider_m.dcp
set_property used_in_implementation false [get_files /home/daniele/Scrivania/Task4/project_Task4_v2.1.1/project_Task4.srcs/sources_1/ip/AXI4_Stream_Divider_m/AXI4_Stream_Divider_m.dcp]
read_vhdl -library xil_defaultlib {
  /home/daniele/Scrivania/Task4/project_Task4_v2.1.1/project_Task4.srcs/sources_1/new/AXI4_Stream_Absolute_Square_m.vhd
  /home/daniele/Scrivania/Task4/project_Task4_v2.1.1/project_Task4.srcs/sources_1/new/abs_sqr_control_unit_m.vhd
  /home/daniele/Scrivania/Task4/project_Task4_v2.1.1/project_Task4.srcs/sources_1/new/abs_sqr_operative_part_m.vhd
  /home/daniele/Scrivania/Task4/project_Task4_v2.1.1/project_Task4.srcs/sources_1/imports/new/register_m.vhd
  /home/daniele/Scrivania/Task4/project_Task4_v2.1.1/project_Task4.srcs/sources_1/imports/new/mod_quad_oper.vhd
  /home/daniele/Scrivania/Task4/project_Task4_v2.1.1/project_Task4.srcs/sources_1/new/AXI4_Stream_Square_Root_m.vhd
  /home/daniele/Scrivania/Task4/project_Task4_v2.1.1/project_Task4.srcs/sources_1/new/Task4_m.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Task4_m -part xc7z010clg400-1


write_checkpoint -force -noxdef Task4_m.dcp

catch { report_utilization -file Task4_m_utilization_synth.rpt -pb Task4_m_utilization_synth.pb }
