# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daniele/Scrivania/Task4/project_Task4_v2.1/project_Task4.srcs/sources_1/ip/AXI4_Stream_Divider_m/AXI4_Stream_Divider_m.xci
# IP: The module: 'AXI4_Stream_Divider_m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniele/Scrivania/Task4/project_Task4_v2.1/project_Task4.srcs/sources_1/ip/AXI4_Stream_Divider_m/AXI4_Stream_Divider_m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI4_Stream_Divider_m'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/daniele/Scrivania/Task4/project_Task4_v2.1/project_Task4.srcs/sources_1/ip/AXI4_Stream_Divider_m/AXI4_Stream_Divider_m.xci
# IP: The module: 'AXI4_Stream_Divider_m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniele/Scrivania/Task4/project_Task4_v2.1/project_Task4.srcs/sources_1/ip/AXI4_Stream_Divider_m/AXI4_Stream_Divider_m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI4_Stream_Divider_m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
