# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.srcs/sources_1/ip/Square/Square.xci
# IP: The module: 'Square' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.srcs/sources_1/ip/Square/Square_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Square'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.srcs/sources_1/ip/Square/Square.xci
# IP: The module: 'Square' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.srcs/sources_1/ip/Square/Square_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Square'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
