# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.cache/wt} [current_project]
set_property parent.project_path {C:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo {c:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet {{C:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.srcs/sources_1/ip/SQRT/SQRT.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.srcs/sources_1/ip/SQRT/SQRT.dcp}}]
add_files -quiet {{C:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.srcs/sources_1/ip/DIVISORE/DIVISORE.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.srcs/sources_1/ip/DIVISORE/DIVISORE.dcp}}]
add_files -quiet {{C:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.srcs/sources_1/ip/Square/Square.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.srcs/sources_1/ip/Square/Square.dcp}}]
add_files -quiet {{C:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.srcs/sources_1/ip/c_addsub_0/c_addsub_0.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.srcs/sources_1/ip/c_addsub_0/c_addsub_0.dcp}}]
read_vhdl -library xil_defaultlib {
  {C:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.srcs/sources_1/new/modulo_quadro.vhd}
  {C:/Users/giann/Desktop/PROGETTO FINALE/versione 1 - tutto xilinx/project_Task4/project_Task4.srcs/sources_1/new/Task4.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Task4 -part xc7z010clg400-1


write_checkpoint -force -noxdef Task4.dcp

catch { report_utilization -file Task4_utilization_synth.rpt -pb Task4_utilization_synth.pb }
